trigger:
  branches:
    include:
      - main
      - development
      - feature/*

pool:
  name: 'Chandan-Windows'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test --configuration $(buildConfiguration) --no-build
  displayName: 'dotnet test $(buildConfiguration)'